### ISSUE TITLE
Google App Engine(GAE)

### ISSUE THREAD

**Issue by rodolfoliviero** [caelum/vraptor-scaffold#17]
Generate project that works on GAE

**Comment by rodolfoliviero** [comment]
some resources about this issue.
http://www.guj.com.br/java/232885-vraptor-scaffold-em-projetos-gae
https://github.com/arthurmc/vraptor-gae-ant-ivy-objectify-blank-project

**Comment by armoucar** [comment]
maybe this issue should be closed.
A pull about GAE feature is running. :)

**Comment by rodolfoliviero** [comment]
yeah....closing
