### ISSUE TITLE
scaffolding something with uppercase

### ISSUE THREAD

**Issue by adrianoalmeida7** [caelum/vraptor-scaffold#19]
when doing a scaffold Item (with uppercase i)

the generated controller generates de following method:

public Item show(Item Item) {...}

Note that the parameter name has an uppercase i also. this should be lowercase.

**Comment by rodolfoliviero** [comment]
Done by adrianoalmeida7

https://github.com/caelum/vraptor-scaffold/commit/f9a5a5e471a86cef8ea82539e534b9410af3909b
