### ISSUE TITLE
Documentation on vraptor

### ISSUE THREAD

**Issue by guilhermesilveira** [caelum/vraptor-scaffold#2]
Create a section explaining vraptor-scaffold usage on vraptor github project documentation

**Comment by rodolfoliviero** [comment]
I created a branch on my vraptor's fork called scaffold-doc.
http://github.com/rodolfoliviero/vraptor/tree/scaffold-doc

**Comment by rodolfoliviero** [comment]
en and pt version are done.
Closing.
