### ISSUE TITLE
Genarated project doesn't run on Eclipse's tomcat

### ISSUE THREAD

**Issue by lucascs** [caelum/vraptor-scaffold#23]
I couldn't run the project on Eclipse via Tomcat.
It complains about hsqldb:

```
Caused by: org.hsqldb.HsqlException: old version database must be shutdown
```

**Comment by rodolfoliviero** [comment]
I tried to simulate the problem.
I created a app and scaffold a model called product, after that i run the project on eclipse via tomcat and its works.

can you  tell me what steps you did?

**Comment by lucascs** [comment]
I think I know what is the problem:

this line from persistence.xml:
    <property name="hibernate.connection.url" value="jdbc:hsqldb:file:tmp/devdb" />

creates a database on my home folder: ~/tmp/devdb.\* when running from eclipse...

I guess I run an older version of hsqldb with this very configuration, so the newer version showed me the error above...
When I deleted the ~/tmp folder, the error stopped.

Maybe there is a way to guarantee that the tmp folder is created on the project folder.
If not, I don't think this issue is fixable, so you can close it.

[]'s

**Comment by rodolfoliviero** [comment]
when use ant jetty.run the tmp folder is created inside project folder,
when import the project on eclipse tmp folder is created on home directory, i dont know why this happens, maybe this is a eclipse issue.

**Comment by lucascs** [comment]
ok then...
closing the issue
thanks
