### ISSUE TITLE
Using minify for CSS and JS files.

### ISSUE THREAD

**Issue by garcia-jj** [caelum/vraptor-scaffold#27]
As discussed here: http://groups.google.com/group/caelum-vraptor-dev/browse_thread/thread/169558165ccc34c2

Add a minify ant task to minify CSS and JS files. There are an example here that uses YUI compressor. https://gist.github.com/759892

Regards

**Comment by rodolfoliviero** [comment]
Garcia Thanks to share this task.

Done.
https://github.com/caelum/vraptor-scaffold/commit/ae9008377b80d394ada8b2ad6d95961356cc7631
