### ISSUE TITLE
list available plugins

### ISSUE THREAD

**Issue by rodolfoliviero** [caelum/vraptor-scaffold#42]
vraptor plugin known should list all plugins that are possible to install.

**Comment by guilhermesilveira** [comment]
hould this one list vraptor plugins or vraptor-scaffold plugins?
we can force gem names to start with vraptor- so we can easily list them, but its harder to list vraptor plugins because their organization will change. unless we use mvnrepository (which is non official)

**Comment by rodolfoliviero** [comment]
I think we should put all of availables plugins in a hash. So it will be easy to list all of them.

**Comment by guilhermesilveira** [comment]
The advantage of not being hard coded is that anyone can create a plugin
even without a pull request to any proj. What do you yhink?

Guilherme Silveira

On 19/05/2011 4:36 PM, "rodolfoliviero" <
reply@reply.github.com>
wrote:

I think we should put all of availables plugins in a hash. So it will be
easy to list all of them.

## 

Reply to this email directly or view it on GitHub:
https://github.com/caelum/vraptor-scaffold/issues/42#comment_1205808

**Comment by rodolfoliviero** [comment]
It is really advantage but if we dont have control of this information we cannot list available plugins. 
So we cannot implements this issue.
