### ISSUE TITLE
list installed plugins

### ISSUE THREAD

**Issue by rodolfoliviero** [caelum/vraptor-scaffold#43]
vraptor plugin list should show all plugins that are already been installed

**Comment by guilhermesilveira** [comment]
can I split into vraptor or vraptor-scaffold plugins?
one is listing inside a section of a config file. another one is listing the gems installed.

**Comment by rodolfoliviero** [comment]
what about after install plugin configure in vraptor-scaffold.properties? So we can read this file and list the installed plugins

**Comment by guilhermesilveira** [comment]
The prob is that the user might remove it from tbe pom.xml but not from the
properties. What do u think?

Guilherme Silveira

On 19/05/2011 4:42 PM, "rodolfoliviero" <
reply@reply.github.com>
wrote:

what about after install plugin configure in vraptor-scaffold.properties? So
we can read this file and list the installed plugins

## 

Reply to this email directly or view it on GitHub:
https://github.com/caelum/vraptor-scaffold/issues/43#comment_1205842

**Comment by rodolfoliviero** [comment]
There is a big difference. The devs changes the pom.xml all the time adding and removind dep, plugins and can delete the comment involuntarily. The file vraptor.properties is a configuration file of scaffold and the dev cannot change it when dev changes it assumes the possibility that the scaffold may not work correctly.

**Comment by guilhermesilveira** [comment]
Hi Rodolfo

You are right
Its a personal taste. I prefer guessing from the pom or similar than
guessing from the config file. Either way the dev might mess up the pom file
(not the properties one.. That one if he changes it means he is responsible
for it)

Regarda

Guilherme Silveira

On 20/05/2011 1:08 AM, "rodolfoliviero" <
reply@reply.github.com>
wrote:

There is a big difference. The devs changes the pom.xml all the time adding
and removind dep, plugins and can delete the comment involuntarily. The file
vraptor.properties is a configuration file of scaffold and the dev cannot
change it when dev changes it assumes the possibility that the scaffold may
not work correctly.

## 

Reply to this email directly or view it on GitHub:
https://github.com/caelum/vraptor-scaffold/issues/43#comment_1207972
