### ISSUE TITLE
install plugin

### ISSUE THREAD

**Issue by rodolfoliviero** [caelum/vraptor-scaffold#44]
vraptor plugin install pluginName should install the plugin

**Comment by guilhermesilveira** [comment]
rodolfo, can I consider this issue just to install a vraptor plugin and open another one for installing a vraptor-scaffold (gem) plugin? both are installed with the same command, but they have different usages

**Comment by rodolfoliviero** [comment]
ok. This issue can only configure the dependencie in a pom.xml or similar file. After finish that we can open another to improve the plugin configuration and generators.

**Comment by rodolfoliviero** [comment]
this was already done. Closing.
