### ISSUE TITLE
update jquery

### ISSUE THREAD

**Issue by rodolfoliviero** [caelum/vraptor-scaffold#54]
jquery has a new version. so we need to update it.

**Comment by lucascs** [comment]
Is the new version compatible with major jquery plugins already?

**Comment by rodolfoliviero** [comment]
I read in the jquery 1.6 release notes that some existing code should be changed, but i dont know if there are many plugins broken. There are some place where we can find this kind of information?

**Comment by lucascs** [comment]
usually http://plugins.jquery.com, or on the plugin site.

you could create a configuration to choose jquery's version, downloading it from google cdn:
https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js

replacing 1.4.2 to the desired version

1.4.x is largely supported, so it should be the default, what do you think?

**Comment by rodolfoliviero** [comment]
It's a good approach. With this issue we dont need to update jquery every time a new version is released

**Comment by rodolfoliviero** [comment]
sample code to read remote files
require 'open-uri'
Kernel::open('http://code.jquery.com/jquery-1.5.1.js').read

**Comment by lucascs** [comment]
It would be easier to use google cdn, pointing to minified version:
https://ajax.googleapis.com/ajax/libs/jquery/<version>/jquery.min.js

**Comment by rodolfoliviero** [comment]
ok.
http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js
this cdn return every time the latest jquery version. We should point to that. So if the user wanna use another jquery version he can specify. 
EX: vraptor new store -J 1.4.2.
what you think about?

**Comment by lucascs** [comment]
sounds like fun ;)
