### ISSUE TITLE
Ant and Jetty (hot deploy)

### ISSUE THREAD

**Issue by felipefontoura** [caelum/vraptor-scaffold#58]
When I create a vraptor project with ant, it don't redeploy/reload automaticaly in jetty when I execute compile and war task.

I used 1.1.0 version.

Thanks

**Comment by rodolfoliviero** [comment]
Felipe, 
I create this gist <code>https://gist.github.com/1043774</code> to fix the hot deploy. It works to me.
Can you test it?
You can find more information here <code>http://docs.codehaus.org/display/JETTY/Ant+Jetty+Plugin</code>

**Comment by felipefontoura** [comment]
Worked fine!

But didn't work with hsqldb (error on lock file).

PS: When I changed to mysql worked.

Thanks!

**Comment by felipefontoura** [comment]
I updated hsqldb to 2.2.0 in ivy.xml and worked fine!

**Comment by rodolfoliviero** [comment]
Done by felipe and merge already done.
